test:
  adapter:     sqlite3
  database:    test.sqlite3
  pool:        5
  timeout:     5000

foo:
  test:
    adapter:     sqlite3
    database:    test_foo.sqlite3
    pool:        5
    timeout:     5000

bar:
  test:
    adapter:     sqlite3
    database:    test_bar.sqlite3
    pool:        5
    timeout:     5000
